steps:
  install:
    image: danlynn/ember-cli:4.12.1
    commands:
      - npm ci
  lint-js:
    image: danlynn/ember-cli:4.12.1
    group: lint
    commands:
      - npm run lint:js --workspaces --if-present
  lint-hbs:
    image: danlynn/ember-cli:4.12.1
    group: lint
    commands:
      - npm run lint:hbs --workspaces --if-present
  dependency-lint:
    image: danlynn/ember-cli:4.12.1
    group: lint
    commands:
      - ember dependency-lint
  test:
    image: danlynn/ember-cli:4.12.1
    commands:
      - npm run test:ember
    failure: ignore
when:
  event: pull_request
